services:
  - type: web
    name: dunnies-store
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      - name: uploads
        mountPath: /opt/render/project/.uploads
        sizeGB: 2
